# NumPy masked array演示

In [1]:
import numpy as np

我们建立一个masked array：

In [2]:
a = np.ma.masked_array(
    data=[1, -1, 2, np.nan],
    mask=[False, True, False, True]
    ); a

masked_array(data=[1.0, --, 2.0, --],
             mask=[False,  True, False,  True],
       fill_value=1e+20)

其中`a`的`data`是：

In [3]:
adata = a.data; adata

array([ 1., -1.,  2., nan])

我们看看`adata`是否等于`a.data`，即`a.data`是否等于它自己：

In [4]:
adata == a.data

array([ True,  True,  True, False])

In [5]:
adata != a.data

array([False, False, False,  True])

`np.nan`不等于任何东西，包括`np.nan`自己：

In [6]:
print(np.nan is np.nan, np.nan == np.nan, np.nan != np.nan)

True False True


除此特例外，前3个元素确实相等。

下面我们看看`a`是否等于它自己的`data`，即上面定义的`adata`：

In [7]:
a == adata

masked_array(data=[True, --, True, --],
             mask=[False,  True, False,  True],
       fill_value=True)

masked array `a` 和 array `adata` 进行二元运算`==`得到的是一个masked array，它的`data`是：

In [8]:
(a == adata).data

array([ True, False,  True, False])

然而，常用的很多函数在masked array上计算时会忽略masked value（这也是为什么我们会用masked array的原因之一），而不是使用masked array的data计算：

In [9]:
np.sum(a == adata), np.all(a == adata), np.any(~(a==adata))

(2, True, False)

所以，即使`not np.all((a == adata).data)`，仍然有`np.all(a == adata)`。这可能是初看上去反直觉的事。

In [10]:
not np.all((a == adata).data), np.all(a == adata)

(True, True)